### ISSUE TITLE
The hyper-parameter used in MSPAN

### ISSUE THREAD

**Issue by benson1016087** [yl3800/EIGV#2]
Hi, 

I'm curious about what hyper parameter you used in training MSPAN (num_scales, K, T) w/ EIGV and w/o EIGV.
Since I use the default value in your work to reproduce training codes, while it can't meet the performance in the paper.

Benson

**Comment by yl3800** [comment]
Hi, the code in this repo is for the HGA baseline, which performs best on NExT-QA. If you are trying to reproduce the result on the MSPAN by yourself, here is the hyperparameter setting I used K=2_T=1_num_scale=4.
